UKM:
    url: //ukm.no/
    title: UKM
    #color: d4c8e4
    scheme: 'default'
    pages:
        - 
            id: forsiden
            url: //ukm.no/
            title: Forsiden
            description: Ung kultur møtes
        -
            # Fra gammel meny
            id: derdubor
            url: //ukm.no/derdubor/
            title: Der du bor
        - 
            id: login
            url: //ukm.no/wp-login.php/
            title: logg inn
            description: Logg inn som lokalkontakt
        - 
            id: festivalen
            url: //festivalen.ukm.no/
            title: festivalen
            description: Alt om UKM-festivalen
        - 
            id: redaksjonelt
            url: //liker.ukm.no/
            title: Nyheter
            description: 
#        - 
#            id: ukmere
#            url: //ukm.no/blog/category/kjente-ukmere/
#            title: Kjente UKMere
#            description: 
        - 
            # Fra gammel meny
            id: pressebilder
            url: //www.flickr.com/photos/ukm/albums
            title: UKM på flickr
            target: _blank
#        - 
#            id: tidligerear
#            url: //ukm.no/tidligere-ar/
#            title: Arkiv
#            description: Bli kjent med oss
        -
            # Fra gammel meny
            id: deltalogin
            url: //delta.ukm.no/
            title: Din side
            description: Endre din påmelding


navbar: 
    url: //ukm.no/wp-login.php/
    title: logg inn
    description: Logg inn som lokalkontakt
    #color: d4c8e4
    scheme: 'default'
    pages:
        -
            id: aktiviteter
            url: //ukm.no/aktiviteter/
            title: Aktiviteter
            description: Alt om UKM-festivalen
        -
            id: ukmfestivalen
            url: //ukm.no/festivalen/
            title: UKM-festivalen
            description: Alt om UKM-festivalen
        - 
            id: redaksjonelt
            url: //liker.ukm.no/
            title: Nyheter
            description: 
                              

ukm:
    url: //ukm.no/hva-er/
    title: Dette er UKM
    #color: d4c8e4
    scheme: 'default'
    pages:
        - 
            id: hvaerukm
            url: //ukm.no/hva-er/
            title: Hva er UKM?
            description: Hva skjer på UKM
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill:hsla(222, 18%, 43%, 1);"><path d="M12 4C9.243 4 7 6.243 7 9h2c0-1.654 1.346-3 3-3s3 1.346 3 3c0 1.069-.454 1.465-1.481 2.255-.382.294-.813.626-1.226 1.038C10.981 13.604 10.995 14.897 11 15v2h2v-2.009c0-.024.023-.601.707-1.284.32-.32.682-.598 1.031-.867C15.798 12.024 17 11.1 17 9c0-2.757-2.243-5-5-5zm-1 14h2v2h-2z"></path></svg>
        -
            id: hvorforukm 
            url: //ukm.no/hvorfor/
            title: Hvorfor delta?
            description: Er UKM for meg
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" style="fill:hsla(222, 18%, 43%, 1);" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z" clip-rule="evenodd" /></svg>
        -
            id: some
            url: //ukm.no/some/
            title: Finn oss på some
            description: 
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill:hsla(222, 18%, 43%, 1);"><path d="M20.947 8.305a6.53 6.53 0 0 0-.419-2.216 4.61 4.61 0 0 0-2.633-2.633 6.606 6.606 0 0 0-2.186-.42c-.962-.043-1.267-.055-3.709-.055s-2.755 0-3.71.055a6.606 6.606 0 0 0-2.185.42 4.607 4.607 0 0 0-2.633 2.633 6.554 6.554 0 0 0-.419 2.185c-.043.963-.056 1.268-.056 3.71s0 2.754.056 3.71c.015.748.156 1.486.419 2.187a4.61 4.61 0 0 0 2.634 2.632 6.584 6.584 0 0 0 2.185.45c.963.043 1.268.056 3.71.056s2.755 0 3.71-.056a6.59 6.59 0 0 0 2.186-.419 4.615 4.615 0 0 0 2.633-2.633c.263-.7.404-1.438.419-2.187.043-.962.056-1.267.056-3.71-.002-2.442-.002-2.752-.058-3.709zm-8.953 8.297c-2.554 0-4.623-2.069-4.623-4.623s2.069-4.623 4.623-4.623a4.623 4.623 0 0 1 0 9.246zm4.807-8.339a1.077 1.077 0 0 1-1.078-1.078 1.077 1.077 0 1 1 2.155 0c0 .596-.482 1.078-1.077 1.078z"></path><circle cx="11.994" cy="11.979" r="3.003"></circle></svg> 
        -
            id: faq
            url: //ukm.no/faq/
            title: Ofte stilte spørsmål
            description: 
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill:hsla(222, 18%, 43%, 1);"><path d="M12 2C6.486 2 2 5.589 2 10c0 2.908 1.897 5.516 5 6.934V22l5.34-4.004C17.697 17.852 22 14.32 22 10c0-4.411-4.486-8-10-8zm-2.5 9a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"></path></svg>

ukmhvorfor:
    url: //ukm.no/
    title: Hvorfor har vi UKM
    #color: d4c8e4
    scheme: 'default'
    pages:
        - 
            id: utenforskap
            url: //bak.ukm.no/hvorfor/utenforskap/
            title: Utenforskap
            description: 
        -
            id: talentutvikling
            url: //bak.ukm.no/hvorfor/talentfabrikk/
            title: Talentutvikling
            description: Er UKM for meg
        -
            id: folkehelse
            url: //bak.ukm.no/hvorfor/folkehelse/
            title: Folkehelse
            description:  
        -
            id: samfunnsutvikling
            url: //bak.ukm.no/hvorfor/samfunnsutvikling/
            title: Samfunnsutvikling
            description:  

samarbeid:
    url: //ukm.no/
    title: I samarbeid med andre 
    #color: d4c8e4
    scheme: 'default'
    pages:
        -
            id: partnere
            url: //bak.ukm.no/samarbeidspartnere/
            title: Partnere
            description: Er UKM for meg
        -
            id: intensjonsavtale
            url: //bak.ukm.no/samarbeidspartnere/intensjonsavtalen/
            title: Bli partner
            description:  


prosjekter:
    url: //ukm.no/
    title: Digitale satsninger
    #color: d4c8e4
    scheme: 'default'
    pages:
        -
            id: norcup
            url: //bak.ukm.no/prosjekter/norcup/
            title: Norgescupen
            description:
        -
            id: stimuleringsmidler
            url: //bak.ukm.no/prosjekter/stimuleringsmidler/
            title: Stimuleringsmidler
            description:  
        -
            id: festivalen
            url: //bak.ukm.no/prosjekter/festivalen/
            title: Festivalen
            description:  
        -
            id: moteplassdatakultur
            url: //bak.ukm.no/prosjekter/moteplass-datakultur/
            title: Møteplass datakultur
            description: 


metodikk:
    url: //ukm.no/
    title: Medvirkning
    #color: d4c8e4
    scheme: 'default'
    pages:
        - 
            id: medvirkning
            url: //bak.ukm.no/metodikk/medvirkning/
            title: Medvirkning
            description: 
        -
            id: samarbeid
            url: //bak.ukm.no/metodikk/samarbeid/
            title: Samarbeid
            description:
        -
            id: lokalforankring
            url: //bak.ukm.no/metodikk/lokal-forankring/
            title: Lokal forankring
            description:  


vibakukm:
    url: //bak.ukm.no/
    title: Organisasjon og historikk
    #color: d4c8e4
    scheme: 'default'
    pages:
        - 
            id: hvaerukm
            url: //bak.ukm.no/hva-er/
            title: Om UKM
            description: Hva skjer på UKM
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="hsla(222, 18%, 43%, 1)"><path d="M11 3a1 1 0 10-2 0v1a1 1 0 102 0V3zM15.657 5.757a1 1 0 00-1.414-1.414l-.707.707a1 1 0 001.414 1.414l.707-.707zM18 10a1 1 0 01-1 1h-1a1 1 0 110-2h1a1 1 0 011 1zM5.05 6.464A1 1 0 106.464 5.05l-.707-.707a1 1 0 00-1.414 1.414l.707.707zM5 10a1 1 0 01-1 1H3a1 1 0 110-2h1a1 1 0 011 1zM8 16v-1h4v1a2 2 0 11-4 0zM12 14c.015-.34.208-.646.477-.859a4 4 0 10-4.954 0c.27.213.462.519.476.859h4.002z" /></svg>
        - 
            id: blogg
            url: //bak.ukm.no/nyheter/
            title: Blogg
            description: Meninger
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill:hsla(222, 18%, 43%, 1);"><path d="M4 19h16v2H4zm0-4h11v2H4zm0-4h16v2H4zm0-8h16v2H4zm0 4h11v2H4z"></path></svg>
        -
            id: historikk
            url: //bak.ukm.no/historien/
            title: Historikk
            description:
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="hsla(222, 18%, 43%, 1)"><path fill-rule="evenodd" d="M10.496 2.132a1 1 0 00-.992 0l-7 4A1 1 0 003 8v7a1 1 0 100 2h14a1 1 0 100-2V8a1 1 0 00.496-1.868l-7-4zM6 9a1 1 0 00-1 1v3a1 1 0 102 0v-3a1 1 0 00-1-1zm3 1a1 1 0 012 0v3a1 1 0 11-2 0v-3zm5-1a1 1 0 00-1 1v3a1 1 0 102 0v-3a1 1 0 00-1-1z" clip-rule="evenodd" /></svg>
        -
            id: kontakt
            url: //bak.ukm.no/kontakt/
            title: Kontaktinformasjon
            description:
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="hsla(222, 18%, 43%, 1)"><path fill-rule="evenodd" d="M14.243 5.757a6 6 0 10-.986 9.284 1 1 0 111.087 1.678A8 8 0 1118 10a3 3 0 01-4.8 2.401A4 4 0 1114 10a1 1 0 102 0c0-1.537-.586-3.07-1.757-4.243zM12 10a2 2 0 10-4 0 2 2 0 004 0z" clip-rule="evenodd" /></svg>  
        -
            id: grafikk
            url: //bak.ukm.no/grafisk-profil/
            title: Logoer og grafisk
            description:  
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill:hsla(222, 18%, 43%, 1);"><path d="M9.38 21.646A9.985 9.985 0 0 0 12 22l.141-.001a2.998 2.998 0 0 0 2.515-1.425c.542-.876.6-1.953.153-2.88l-.198-.415c-.453-.942-.097-1.796.388-2.281.485-.485 1.341-.841 2.28-.388h.001l.413.199a2.99 2.99 0 0 0 2.881-.153A2.997 2.997 0 0 0 22 12.141a9.926 9.926 0 0 0-.353-2.76c-1.038-3.827-4.353-6.754-8.246-7.285-3.149-.427-6.241.602-8.471 2.833S1.666 10.247 2.096 13.4c.53 3.894 3.458 7.208 7.284 8.246zM15.5 6a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3zm-5-1a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3zM9 15.506a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm-2.5-6.5a1.5 1.5 0 1 1-.001 3.001A1.5 1.5 0 0 1 6.5 9.006z"></path></svg>


personvern:
    url: //personvern.ukm.no/
    title: Personvernpolitikk
    scheme: 'default'
    pages:
        - 
            id: pamelding
            url: //personvern.ukm.no/pamelding/
            title: Informasjon ved påmelding
            description:
        -
            id: datalagring
            url: //personvern.ukm.no/datalagring/
            title: Datalagring
            description:
        -
            id: informasjonskapsler
            url: //personvern.ukm.no/informasjonskapsler/
            title: Informasjonskapsler
            description:  
        -
            id: dokumentasjon
            url: //personvern.ukm.no/dokumentasjon/
            title: Alt om vår dokumentasjon
            description:  


# v Fra gammel meny
egoego:
    url: //liker.ukm.no/
    title: Redaksjonelt
    scheme: 'default'
    pages:
        - 
            id: forsiden
            url: //liker.ukm.no/
            title: Forsiden
            description:
#        - 
#            id: egoom
#            url: //liker.ukm.no/om-oss/
#            title: Hva er ego?
#            description:
#        -
#            id: egokontakt
#            url: //liker.ukm.no/kontakt/
#            title: Kontakt oss

# v Fra gammel meny
organisasjonen:
    url: //org.ukm.no/
    title: Organisasjonen
    scheme: 'cherry'
    pages:
        - 
            id: forsiden
            url: //org.ukm.no/
            title: Nyheter
        - 
            id: presse
            url: //org.ukm.no/presse/
            title: Presse
        - 
            id: kontakt
            url: //org.ukm.no/kontakt/
            title: Kontakt oss
        - 
            id: ukmsjefen
            url: //org.ukm.no/category/ukmsjefen/
            title: UKM-sjefen
        - 
            id: festivalen
            url: //org.ukm.no/festivalen/
            title: UKM-festivalen
        -
            id: stimuleringsmidler
            url: //org.ukm.no/stimuleringsmidler/
            title: Stimuleringsmidler
        -
            id: MGPjr
            url: //org.ukm.no/mgpjr/
            title: MGPjr-samarbeid
        -
            id: historikk
            url: //org.ukm.no/historikk/
            title: Historikk
        - 
            id: statistikk
            url: //org.ukm.no/statistikk/
            title: Statistikk
        - 
            id: grafikk
            url: //org.ukm.no/grafisk-profil/
            title: Grafisk profil

#        - 
#            id: historikk
#            url: //org.ukm.no/historikk/
#            title: Historikk
#        - 
#            id: verdier
#            url: //org.ukm.no/verdier/
#            title: Verdier

        - 
            id: cookies
            url: //personvern.ukm.no/
            title: Personvernpolitikk
        - 
            id: creativecommons
            url: //org.ukm.no/vilkar/
            title: Vilkår for bruk av innhold

            
ukmtv:
    url: //tv.ukm.no
    title: UKM-TV
    scheme: 'dark'
    pages:
        -
            id: sok
            url: //tv.ukm.no/search/
            title: Søk
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill:hsla(222, 18%, 43%, 1);"><path d="M19.023 16.977a35.13 35.13 0 0 1-1.367-1.384c-.372-.378-.596-.653-.596-.653l-2.8-1.337A6.962 6.962 0 0 0 16 9c0-3.859-3.14-7-7-7S2 5.141 2 9s3.14 7 7 7c1.763 0 3.37-.66 4.603-1.739l1.337 2.8s.275.224.653.596c.387.363.896.854 1.384 1.367l1.358 1.392.604.646 2.121-2.121-.646-.604c-.379-.372-.885-.866-1.391-1.36zM9 14c-2.757 0-5-2.243-5-5s2.243-5 5-5 5 2.243 5 5-2.243 5-5 5z"></path></svg>
        -
            id: festival
            url: //tv.ukm.no/festivalen/
            title: UKM-festivalen
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" style="fill:hsla(222, 18%, 43%, 1);"><path d="M21.947,9.179c-0.129-0.378-0.47-0.645-0.868-0.676L15.378,8.05l-2.467-5.461C12.75,2.23,12.393,2,12,2 s-0.75,0.23-0.911,0.588L8.622,8.05L2.921,8.503C2.53,8.534,2.193,8.791,2.06,9.16s-0.039,0.782,0.242,1.056l4.213,4.107 l-1.49,6.452c-0.092,0.399,0.069,0.814,0.406,1.047C5.603,21.94,5.801,22,6,22c0.193,0,0.387-0.056,0.555-0.168L12,18.202 l5.445,3.63c0.348,0.232,0.805,0.223,1.145-0.024c0.338-0.247,0.487-0.68,0.372-1.082l-1.829-6.4l4.536-4.082 C21.966,9.976,22.075,9.558,21.947,9.179z"></path></svg>
        -
            id: fylke
            url: //tv.ukm.no/fylke/
            title: Fylkesfestivaler
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill:hsla(222, 18%, 43%, 1);"><path d="M19 4h-2V2h-2v2H9V2H7v2H5c-1.103 0-2 .897-2 2v14c0 1.103.897 2 2 2h14c1.103 0 2-.897 2-2V6c0-1.103-.897-2-2-2zm-4.588 15-2.449-1.288L9.514 19l.468-2.728L8 14.342l2.738-.398 1.225-2.48 1.225 2.48 2.738.398-1.981 1.931.467 2.727zM19 9H5V7h14v2z"></path></svg>
        -
            # id: lokal
            # url: //tv.ukm.no/lokal/
            # title: Lokalmønstringer
            # svg: 
        # -
            id: info
            url: //tv.ukm.no/info/
            title: Infovideoer
            svg: <svg class="icon-some" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill:hsla(222, 18%, 43%, 1);"><path d="M19 3H5c-1.103 0-2 .897-2 2v14c0 1.103.897 2 2 2h14c1.103 0 2-.897 2-2V5c0-1.103-.897-2-2-2zM9 11V5h6v6H9zm6 2v6H9v-6h6zM5 5h2v2H5V5zm0 4h2v2H5V9zm0 4h2v2H5v-2zm0 4h2v2H5v-2zm14.002 2H17v-2h2.002v2zm-.001-4H17v-2h2.001v2zm0-4H17V9h2.001v2zM17 7V5h2v2h-2z"></path></svg>

# v Fra gammel meny
arrangorer:
    url: //ukm.no/wp-login.php
    title: UKM-arrangører
    scheme: 'default'
    pages:
        - 
            id: login
            url: //ukm.no/wp-login.php
            title: Logg inn

english:
    url: //org.ukm.no/english
    title: English
    scheme: 'default'
    pages:
        - 
            id: about
            url: //ukm.no/about-ukm/
            title: About UKM

erukmformeg:
    url: //ukm.no/
    title: Er UKM for meg
    scheme: 'default'
    pages:
        - 
            id: erukmformeg
            url: //ukm.no/hvorfor/
            title: Er UKM for meg?
        -
            id: hvaskjerpåukm
            url: //ukm.no/hva-er/
            title: Hva skjer på UKM?
        -
            id: arrangementernaermeg
            url: //ukm.no/fylker/
            title: Arrangementer nær meg?
